flags:
  QAMenu:
    paths: 
      - Sources/QAMenu/
  QAMenuUIKit:
    paths:
      - Sources/QAMenuUIKit/
  QAMenuUtils:
    paths:
      - Sources/QAMenuUtils/
  
# To see status checks based on flags
coverage:
  status:
    project:
      QAMenu:
        flags:
          - QAMenu
      QAMenuUIKit:
        flags:
          - QAMenuUIKit
      QAMenuUtils:
        flags:
          - QAMenuUtils
