default_platform(:ios)

platform :ios do
  
  desc "Runs the AllUnitTests scheme"
  lane :unit_tests do
    run_tests(
      workspace: "QAMenu.xcworkspace",
      scheme: "AllUnitTests"
    )
  end

  desc "Builds the Example-iOS app"
  lane :build_ios_example_app do
    build_app(
      workspace: "QAMenu.xcworkspace",
      scheme: "Example-iOS",
      skip_archive: true,
      skip_codesigning: true
    )
  end

  desc "Builds the Example-SwiftUI (iOS) app"
  lane :build_swiftui_ios_example_app do
    build_app(
      workspace: "QAMenu.xcworkspace",
      scheme: "Example-SwiftUI (iOS)",
      skip_archive: true,
      skip_codesigning: true
    )
  end

  desc "Builds the Example-SwiftUI (watchOS) app"
  lane :build_swiftui_watchos_example_app do
    build_app(
      workspace: "QAMenu.xcworkspace",
      scheme: "Example-SwiftUI (watchOS) WatchKit App",
      skip_archive: true,
      skip_codesigning: true,
      destination: 'generic/platform=watchOS'
    )
  end

  desc "Builds the Example-SwiftUI (macOS) app"
  lane :build_swiftui_macos_playground_app do
    build_app(
      workspace: "QAMenu.xcworkspace",
      scheme: "Playground-SwiftUI (macOS)",
      skip_archive: true,
      skip_codesigning: true
    )
  end

  desc "Builds the Example-SwiftUI (tvOS) app"
  lane :build_swiftui_tvos_playground_app do
    build_app(
      workspace: "QAMenu.xcworkspace",
      scheme: "Playground-SwiftUI (tvOS)",
      skip_archive: true,
      skip_codesigning: true
    )
  end

  desc "Builds the Pod-Integration-iOS-UIKit example apps"
  lane :build_pods_integration_uikit_ios_example_app do
    cocoapods(
      clean_install: true,
      podfile: "Examples/Pod-Integration/Podfile"
    )
    build_app(
      workspace: "Examples/Pod-Integration/Pod-Integration.xcworkspace",
      scheme: "Pod-Integration-iOS-UIKit",
      skip_archive: true,
      skip_codesigning: true
    )
  end

  desc "Builds the Pod-Integration-iOS-SwiftUI example apps"
  lane :build_pods_integration_swiftui_ios_example_app do
    cocoapods(
      clean_install: true,
      podfile: "Examples/Pod-Integration/Podfile"
    )
    build_app(
      workspace: "Examples/Pod-Integration/Pod-Integration.xcworkspace",
      scheme: "Pod-Integration-iOS-SwiftUI",
      skip_archive: true,
      skip_codesigning: true
    )
  end

  desc "Ships Pods for the current version"
  lane :ship_pods do
    add_git_tag(
      tag: File.read('../VERSION')
    )
    push_git_tags

    podspecs = [
      "QAMenuUtils.podspec",
      "QAMenu.podspec",
      "QAMenuUIKit.podspec",
      "QAMenuSwiftUI.podspec",
      "QAMenuCatalog.podspec",
      "QAMenuExampleItems.podspec"
    ]

    podspecs.each { |podspec|
      pod_push(
        path: podspec,
        use_bundle_exec: true,
        synchronous: true
      )
    }
  end
end
