source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

def qamenu_without_renderer
	pod 'QAMenu', path: '../..'
	pod 'QAMenuUtils', path: '../..'
	pod 'QAMenuCatalog', path: '../..'
	pod 'QAMenuExampleItems', path: '../..'
end

target 'Pod-Integration-iOS-UIKit' do
	platform :ios, '10.0'

	qamenu_without_renderer
	pod 'QAMenuUIKit', path: '../..'
end

target 'Pod-Integration-iOS-SwiftUI' do
	platform :ios, '14.0'

	qamenu_without_renderer
	pod 'QAMenuSwiftUI', path: '../..'
end

