name: Unit-Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer

jobs:
  job-unit-tests:
    name: AllUnitTests
    runs-on: macOS-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install bundles
        run: |
          bundle config path Vendor/Bundle
          bundle install --without=documentation --jobs 4 --retry 3

      - name: Run AllUnitTests
        run: bundle exec fastlane unit_tests

      - name: Codecov
        run: |
          Fastlane/codecov.sh
